// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindSetCoach.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MindSetCoach.Api.Migrations
{
    [DbContext(typeof(MindSetCoachDbContext))]
    [Migration("20251227001954_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MindSetCoach.Api.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachId = 1,
                            Email = "athlete1@test.com",
                            Name = "Athlete One",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CoachId = 1,
                            Email = "athlete2@test.com",
                            Name = "Athlete Two",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MindSetCoach.Api.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "coach@test.com",
                            Name = "Coach Mike",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MindSetCoach.Api.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmotionalState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.Property<string>("MentalBarriers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionReflection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("JournalEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AthleteId = 1,
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmotionalState = "Feeling nervous about the upcoming competition. My anxiety is high but I'm trying to stay positive.",
                            EntryDate = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFlagged = true,
                            MentalBarriers = "Self-doubt is creeping in. I keep comparing myself to other athletes and feeling like I'm not good enough.",
                            SessionReflection = "Training went okay today. I struggled with consistency in my technique. Need to focus more on breathing."
                        },
                        new
                        {
                            Id = 2,
                            AthleteId = 1,
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmotionalState = "More confident today after talking with my coach. Feeling motivated.",
                            EntryDate = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFlagged = false,
                            MentalBarriers = "Still worried about letting my team down, but working through it with visualization techniques.",
                            SessionReflection = "Had a great session! My form was much better and I hit all my targets. Coach gave positive feedback."
                        },
                        new
                        {
                            Id = 3,
                            AthleteId = 1,
                            CreatedAt = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmotionalState = "Feeling strong and focused. Ready to push myself today.",
                            EntryDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFlagged = false,
                            MentalBarriers = "Had a moment of doubt during the hardest set, but used my breathing techniques to refocus. It worked!",
                            SessionReflection = "Pushed through a tough workout. My mental game was on point - stayed present and didn't let frustration take over."
                        },
                        new
                        {
                            Id = 4,
                            AthleteId = 1,
                            CreatedAt = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmotionalState = "Tired and a bit overwhelmed. Feeling the pressure of balancing training with life.",
                            EntryDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFlagged = true,
                            MentalBarriers = "Feeling burnt out. The voice in my head keeps saying I should take a break, but I'm afraid of losing momentum.",
                            SessionReflection = "Not my best session. I was distracted and couldn't focus. Made several mistakes that I don't usually make."
                        },
                        new
                        {
                            Id = 5,
                            AthleteId = 1,
                            CreatedAt = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmotionalState = "Recharged after taking yesterday afternoon off. Feeling balanced and ready.",
                            EntryDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFlagged = false,
                            MentalBarriers = "Learning to trust the process and not feel guilty about taking care of myself. This is progress.",
                            SessionReflection = "Amazing session today! Everything clicked. I realized that rest was exactly what I needed."
                        });
                });

            modelBuilder.Entity("MindSetCoach.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "coach@test.com",
                            PasswordHash = "$2a$11$jWRAhGYBJJw4JlX8QWpY5uBQxRBOg3N93ktjv8m9u4XTnXg/2hrw6",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "athlete1@test.com",
                            PasswordHash = "$2a$11$jWRAhGYBJJw4JlX8QWpY5uBQxRBOg3N93ktjv8m9u4XTnXg/2hrw6",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "athlete2@test.com",
                            PasswordHash = "$2a$11$jWRAhGYBJJw4JlX8QWpY5uBQxRBOg3N93ktjv8m9u4XTnXg/2hrw6",
                            Role = 0
                        });
                });

            modelBuilder.Entity("MindSetCoach.Api.Models.Athlete", b =>
                {
                    b.HasOne("MindSetCoach.Api.Models.Coach", "Coach")
                        .WithMany("Athletes")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindSetCoach.Api.Models.User", "User")
                        .WithOne("Athlete")
                        .HasForeignKey("MindSetCoach.Api.Models.Athlete", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindSetCoach.Api.Models.Coach", b =>
                {
                    b.HasOne("MindSetCoach.Api.Models.User", "User")
                        .WithOne("Coach")
                        .HasForeignKey("MindSetCoach.Api.Models.Coach", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindSetCoach.Api.Models.JournalEntry", b =>
                {
                    b.HasOne("MindSetCoach.Api.Models.Athlete", "Athlete")
                        .WithMany("JournalEntries")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("MindSetCoach.Api.Models.Athlete", b =>
                {
                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("MindSetCoach.Api.Models.Coach", b =>
                {
                    b.Navigation("Athletes");
                });

            modelBuilder.Entity("MindSetCoach.Api.Models.User", b =>
                {
                    b.Navigation("Athlete");

                    b.Navigation("Coach");
                });
#pragma warning restore 612, 618
        }
    }
}
